# Generated by Django 3.1.2 on 2022-04-13 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40, verbose_name='Модель')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('image', models.CharField(max_length=100)),
                ('release_date', models.DateField(verbose_name='Дата выпуска')),
                ('lte_exists', models.BooleanField(default=False)),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
            ],
        ),
    ]
